### ISSUE TITLE
♻️ Use reacts power

### ISSUE THREAD

**Issue by astroash** [fac-17/My-Body-Back#115]
https://github.com/fac-17/My-Body-Back/blob/7db9eac41abbc2e77244bb6ce16876cfa4952383/src/components/NotesOfLove/NotesOfLove.js#L20-L29

React is an abstraction layer on top of vanilla dom manipulation. It streamlines a lot for us, and does lot of magic optimisation. We shouldn't be accessing the dom directly. 

`className` is reacts way of passing classes to elements. This is where you should be adding/removing classes. You shouldn't be doing this yourself directly.

Can you think of any ways you could do this? Feel free to @ me if you get stuck.

**Comment by mkatenolan** [comment]
Hey @astroash thanks for bringing this up - actually used this in my last project then forgot about it... did you mean something like this..? 

```
{imageArray.map((image, i) => (
    <img src={image}
    id={i}
    className={this.id == index ? "notes-of-love__image__active" : "notes-of-love__image"}
    />
  ))}
```

**Comment by astroash** [comment]
Yup!

**Comment by astroash** [comment]
Also, just to highlight, you should *never* access the dom directly when using react. If you use `document.` this should sound alarm bells 🔔
