### ISSUE TITLE
Research React Router

### ISSUE THREAD

**Issue by Albadylic** [fac-17/My-Body-Back#48]
Since our app will have many pages perhaps we need a server and router.
- [x] Do we need one?

**Comment by mkatenolan** [comment]
@Albadylic @sarahyjja @frannyfra I've just had a quick look into [react-router-dom](https://reacttraining.com/react-router/web/guides/quick-start) and it is made for client-side routing so no need to build a sever. 

It would be great if we can all have a look into it before Monday so we all know how to use it. It seems reasonably straight forward and the link above talks through the basics. Also a video [here](https://www.youtube.com/watch?v=Law7wfdg_ls) which is half an hour long.
