### ISSUE TITLE
Research Airtable & Lambda Function

### ISSUE THREAD

**Issue by mkatenolan** [fac-17/My-Body-Back#55]
As discussed this afternoon we would like to look into using Airtable as a stretch goal. 

In order to scope this it would be good if we can do a bit of research into using Airtable with React and how we would use Lambda functions to hide our environment variables on Netlify.

**Comment by mkatenolan** [comment]
Video: 

https://www.youtube.com/watch?v=drJwMlD9Mjo&feature=youtu.be

**Comment by Albadylic** [comment]
Closed as research completed and now being implemented in #162
